variables:
    sonar_url: http://172.16.21.32:9000
    sonar_login: trade
    sonar_password: trade

stages:
    - branch
    - trunk

sonar_review:
    stage: branch
    script: "mvn package -U -Denforcer.skip=true --batch-mode verify sonar:sonar -Dsonar.login=$sonar_login -Dsonar.password=$sonar_password -Dsonar.host.url=$sonar_url -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME  -Dsonar.gitlab.project_id=$CI_PROJECT_ID"


sonar:
    stage: trunk
    script: "mvn package -U -Denforcer.skip=true cobertura:cobertura -Dcobertura.report.format=xml sonar:sonar -Dsonar.host.url=$sonar_url"
